--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 9/30/2018 5:28:30 PM
-- Server version: 5.5.5-10.1.35-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE animais;

--
-- Drop table `endereco`
--
DROP TABLE IF EXISTS endereco;

--
-- Drop table `funcionario`
--
DROP TABLE IF EXISTS funcionario;

--
-- Drop table `adocao`
--
DROP TABLE IF EXISTS adocao;

--
-- Drop table `animal`
--
DROP TABLE IF EXISTS animal;

--
-- Drop table `mensagem`
--
DROP TABLE IF EXISTS mensagem;

--
-- Drop table `solicitacao`
--
DROP TABLE IF EXISTS solicitacao;

--
-- Drop table `telefone`
--
DROP TABLE IF EXISTS telefone;

--
-- Drop table `usuario`
--
DROP TABLE IF EXISTS usuario;

--
-- Drop table `pessoa`
--
DROP TABLE IF EXISTS pessoa;

--
-- Set default database
--
USE animais;

--
-- Create table `pessoa`
--
CREATE TABLE pessoa (
  id_pessoa INT(11) NOT NULL AUTO_INCREMENT,
  id_endereco INT(10) DEFAULT NULL,
  nome VARCHAR(60) NOT NULL,
  codigo VARCHAR(15) NOT NULL,
  rg VARCHAR(8) NOT NULL,
  dt_nasc DATE DEFAULT NULL,
  PRIMARY KEY (id_pessoa)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `usuario`
--
CREATE TABLE usuario (
  id_usuario INT(10) NOT NULL AUTO_INCREMENT,
  id_pessoa INT(10) NOT NULL,
  nivel CHAR(1) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  senha VARCHAR(20) DEFAULT NULL,
  token VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id_usuario)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE usuario 
  ADD CONSTRAINT id_pessoa_FK01 FOREIGN KEY (id_pessoa)
    REFERENCES pessoa(id_pessoa) ON DELETE NO ACTION;

--
-- Create table `telefone`
--
CREATE TABLE telefone (
  id_telefone INT(10) NOT NULL AUTO_INCREMENT,
  id_pessoa INT(10) DEFAULT NULL,
  numero VARCHAR(12) DEFAULT NULL,
  PRIMARY KEY (id_telefone)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE telefone 
  ADD CONSTRAINT id_telefone_FK01 FOREIGN KEY (id_pessoa)
    REFERENCES pessoa(id_pessoa) ON DELETE NO ACTION;

--
-- Create table `solicitacao`
--
CREATE TABLE solicitacao (
  id_solicitacao INT(11) NOT NULL AUTO_INCREMENT,
  id_pessoa INT(10) DEFAULT NULL,
  data DATE DEFAULT NULL,
  descricao VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id_solicitacao)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE solicitacao 
  ADD CONSTRAINT id_solicitacao_FK01 FOREIGN KEY (id_pessoa)
    REFERENCES pessoa(id_pessoa) ON DELETE NO ACTION;

--
-- Create table `mensagem`
--
CREATE TABLE mensagem (
  id_mensagem INT(10) NOT NULL AUTO_INCREMENT,
  id_remetente INT(10) NOT NULL,
  id_destinatario INT(10) NOT NULL,
  mensagem TEXT NOT NULL,
  data DATETIME NOT NULL,
  PRIMARY KEY (id_mensagem)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE mensagem 
  ADD CONSTRAINT id_destintario_FK02 FOREIGN KEY (id_destinatario)
    REFERENCES pessoa(id_pessoa) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE mensagem 
  ADD CONSTRAINT id_remetente_FK01 FOREIGN KEY (id_remetente)
    REFERENCES pessoa(id_pessoa) ON DELETE NO ACTION;

--
-- Create table `animal`
--
CREATE TABLE animal (
  id_animal INT(11) NOT NULL AUTO_INCREMENT,
  id_pessoa INT(11) NOT NULL,
  idade VARCHAR(12) NOT NULL,
  raca VARCHAR(15) NOT NULL,
  nome VARCHAR(20) NOT NULL,
  cor VARCHAR(10) NOT NULL,
  porte VARCHAR(10) NOT NULL,
  deficiencia TINYINT(1) NOT NULL,
  sexo VARCHAR(10) NOT NULL,
  vacina TINYINT(1) NOT NULL,
  data_registro DATE NOT NULL,
  castracao TINYINT(1) NOT NULL,
  patologia VARCHAR(20) NOT NULL,
  situacao VARCHAR(255) NOT NULL,
  PRIMARY KEY (id_animal)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `idadotante` on table `animal`
--
ALTER TABLE animal 
  ADD INDEX idadotante(id_pessoa);

--
-- Create table `adocao`
--
CREATE TABLE adocao (
  id_solicitacao INT(11) NOT NULL AUTO_INCREMENT,
  id_pessoa INT(11) NOT NULL,
  id_animal INT(10) DEFAULT NULL,
  data DATE NOT NULL,
  PRIMARY KEY (id_solicitacao)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `idpessoa` on table `adocao`
--
ALTER TABLE adocao 
  ADD INDEX idpessoa(id_pessoa);

--
-- Create foreign key
--
ALTER TABLE adocao 
  ADD CONSTRAINT id_adocao_FK01 FOREIGN KEY (id_pessoa)
    REFERENCES pessoa(id_pessoa) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE adocao 
  ADD CONSTRAINT id_animal_FK02 FOREIGN KEY (id_animal)
    REFERENCES animal(id_animal) ON DELETE NO ACTION;

--
-- Create table `funcionario`
--
CREATE TABLE funcionario (
  id_pessoa INT(11) NOT NULL AUTO_INCREMENT,
  id_func INT(11) NOT NULL,
  email VARCHAR(30) NOT NULL,
  senha VARCHAR(15) NOT NULL,
  PRIMARY KEY (id_pessoa)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `idpessoa` on table `funcionario`
--
ALTER TABLE funcionario 
  ADD INDEX idpessoa(id_func);

--
-- Create table `endereco`
--
CREATE TABLE endereco (
  id_endereco INT(10) NOT NULL AUTO_INCREMENT,
  bairro VARCHAR(20) NOT NULL,
  numero VARCHAR(6) NOT NULL,
  rua VARCHAR(30) NOT NULL,
  cidade VARCHAR(20) NOT NULL,
  estado CHAR(2) DEFAULT NULL,
  resumo VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id_endereco)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table pessoa
--
-- Table animais.pessoa does not contain any data (it is empty)

-- 
-- Dumping data for table animal
--
-- Table animais.animal does not contain any data (it is empty)

-- 
-- Dumping data for table usuario
--
-- Table animais.usuario does not contain any data (it is empty)

-- 
-- Dumping data for table telefone
--
-- Table animais.telefone does not contain any data (it is empty)

-- 
-- Dumping data for table solicitacao
--
-- Table animais.solicitacao does not contain any data (it is empty)

-- 
-- Dumping data for table mensagem
--
-- Table animais.mensagem does not contain any data (it is empty)

-- 
-- Dumping data for table funcionario
--
-- Table animais.funcionario does not contain any data (it is empty)

-- 
-- Dumping data for table endereco
--
-- Table animais.endereco does not contain any data (it is empty)

-- 
-- Dumping data for table adocao
--
-- Table animais.adocao does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;